name: clever_ads_solutions
description: The CAS.AI Flutter plugin allows you to easily monetize your apps for iOS and Android using lot of Ads SDKs in mediation.
version: 0.9.0
repository: https://github.com/cleveradssolutions/CAS-Flutter
documentation: https://github.com/cleveradssolutions/CAS-Flutter/wiki
issue_tracker: https://github.com/cleveradssolutions/CAS-Flutter/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cleveradssolutions.plugin.flutter
        pluginClass: CASFlutter
      ios:
        pluginClass: CASFlutter

topics:
  - ads
  - android
  - ios
